baseurl = "https:/pengjiayou.github.io"
title = "嘉佑的博客"
copyright = "Copyright &copy; 2019 - Author Name"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "彭嘉佑"
    github = "pengjiayou"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = ""
    instagram = ""
    stackoverflow = ""

[params]
    tagline = "A Hugo theme for creative and technical writing"
    description = "Kiera: A Hugo theme for creative and technical writing."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
